# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Topic.create!([{name: "Select From List"},
                {name: "Air law and atc procedures"},
                {name: "airframe and system, electrics, powerplant, em. equipment"},
                {name: "Instruments and electronics"},
                {name: "mass and balance - aeroplanes"},
                {name: "performance - aeroplane"},
                {name: "flight planning and flight monitoring"},
                {name: "human performance"},
                {name: "meterology"},
                {name: "general navigation"},
                {name: "radio navigation"},
                {name: "principles of flight - aeroplane"}
              ])

Topic.create!([{ name: "Select Sub Topic"},
  {name: "ANNEX 1 – PERSONNEL LICENSING", parent_topic_id: 2},
  {name: "ANNEX 7 – AIRCRAFT NATIONALITY AND REGISTRATION MARKS", parent_topic_id: 2},
  {name: "ANNEX 8 - AIRWORTHINESS OF AIRCRAFT", parent_topic_id: 2},
  {name: "ANNEX 11 - AIR TRAFFIC SERVICES (ATS)", parent_topic_id: 2},
  {name: "ANNEX 15 - AERONAUTICAL INFORMATION SERVICE", parent_topic_id: 2},
  {name: "ANNEX 17 - SECURITY", parent_topic_id: 2},
  {name: "Aerodrome Data & Definitions", parent_topic_id: 2},
  {name: "AIRCRAFT ACCIDENT AND INCIDENT INVESTIGATION", parent_topic_id: 2},
  {name: "Altimeter Setting Procedures", parent_topic_id: 2},
  {name: "Applicability of the Rules of the Air", parent_topic_id: 2},
  {name: "Approach Lighting Systems", parent_topic_id: 2},
  {name: "Approach Procedures", parent_topic_id: 2},
  {name: "Calculation of Declared Distances", parent_topic_id: 2},
  {name: "Commercial practices and associated rules", parent_topic_id: 2},
  {name: "Definitions & Organisation", parent_topic_id: 2},
  {name: "Departure Procedures", parent_topic_id: 2},
  {name: "Emergency and Other Services", parent_topic_id: 2},
  {name: "Entry and Departure of Aircraft", parent_topic_id: 2},
  {name: "Entry and departure of persons and their baggage", parent_topic_id: 2},
  {name: "Essential Definitions", parent_topic_id: 2},
  {name: "General Rules", parent_topic_id: 2},
  {name: "Holding Procedures", parent_topic_id: 2},
  {name: "Interception of Civil Aircraft", parent_topic_id: 2},
  {name: "International Agreements", parent_topic_id: 2},
  {name: "Instrument Flight Rules IFR", parent_topic_id: 2},
  {name: "Liabilities towards persons and goods on the ground", parent_topic_id: 2},
  {name: "Operating Procedures", parent_topic_id: 2},
  {name: "Search and Rescue Signals", parent_topic_id: 2},
  {name: "Signals", parent_topic_id: 2},
  {name: "Tables of cruising levels", parent_topic_id: 2},
  {name: "The Convention of Chicago", parent_topic_id: 2},
  {name: "The PIC’s authority and responsibility regarding safety and security", parent_topic_id: 2},
  {name: "Transponder Operating Procedures", parent_topic_id: 2},
  {name: "Visual Aids for Navigation", parent_topic_id: 2},
  {name: "Visual Aids for Denoting Obstacles", parent_topic_id: 2},
  {name: "Visual aids for Denoting Areas of Restrictive Use", parent_topic_id: 2},
  {name: "Visual Flight Rules VFR", parent_topic_id: 2}])

Topic.create!([{ name: "Select Sub Topic"},
  { name: "Fuel system", parent_topic_id: 3 },
  { name: "Fuselage", parent_topic_id: 3 },
  { name: "Cockpit and cabin windows", parent_topic_id: 3 },
  { name: "Wing", parent_topic_id: 3 },
  { name: "Stabilising surfaces", parent_topic_id: 3 },
  { name: "Landing Gear", parent_topic_id: 3 },
  { name: "Flight controls (construction and operation)", parent_topic_id: 3 },
  { name: "Hydraulics", parent_topic_id: 3 },
  { name: "Air Driven systems (piston engines only)", parent_topic_id: 3 },
  { name: "Air driven Systems (Turbo Propeller and Jet Aircraft)", parent_topic_id: 3 },
  { name: "Non-pneumatic operated de-ice and anti-ice systems", parent_topic_id: 3 },
  { name: "Direct current (DC)", parent_topic_id: 3 },
  { name: "Alternating current (AC)", parent_topic_id: 3 },
  { name: "Semiconductor", parent_topic_id: 3 },
  { name: "Basic knowledge of computers", parent_topic_id: 3 },
  { name: "Basic radio propagation theory", parent_topic_id: 3 },
  { name: "Piston Engine", parent_topic_id: 3 },
  { name: "Turbine Engine", parent_topic_id: 3 },
  { name: "Engine Construction", parent_topic_id: 3 },
  { name: "Engine Systems", parent_topic_id: 3 },
  { name: "Auxiliary Power Unit (APU)", parent_topic_id: 3 },
  { name: "Doors and Emergency Exits", parent_topic_id: 3 },
  { name: "Smoke detection", parent_topic_id: 3 },
  { name: "Fire detection", parent_topic_id: 3 },
  { name: "Fire Fighting Equipment", parent_topic_id: 3 },
  { name: "Aircraft oxygen equipment", parent_topic_id: 3 },
  { name: "Emergency equipment", parent_topic_id: 3 }])

Topic.create!([{ name: "Select Sub Topic"},
  { name: "Air Data Instruments", parent_topic_id: 4},
  { name: "Gyroscopic Instruments", parent_topic_id: 4},
  { name: "Magnetic Compass", parent_topic_id: 4},
  { name: "Radio Altimeter", parent_topic_id: 4},
  { name: "Electronic Flight Instrument System (EFIS)", parent_topic_id: 4},
  { name: "Flight Management System (FMS)", parent_topic_id: 4},
  { name: "Flight Director", parent_topic_id: 4},
  { name: "Autopilot", parent_topic_id: 4},
  { name: "Flight Envelope Protection", parent_topic_id: 4},
  { name: "Yaw Damper", parent_topic_id: 4},
  { name: "Automatic Pitch Trim", parent_topic_id: 4},
  { name: "Thrust Computation", parent_topic_id: 4},
  { name: "Auto Thrust", parent_topic_id: 4},
  { name: "Warnings general", parent_topic_id: 4},
  { name: "Altitude Alert System", parent_topic_id: 4},
  { name: "Ground Proximity Warning System", parent_topic_id: 4},
  { name: "Traffic Collision Avoidance System TCAS II", parent_topic_id: 4},
  { name: "Overspeed Warning", parent_topic_id: 4},
  { name: "Stall Warning System", parent_topic_id: 4},
  { name: "Flight Data Recorder", parent_topic_id: 4},
  { name: "Cockpit Voice Recorder", parent_topic_id: 4},
  { name: "Pressure Gauge", parent_topic_id: 4},
  { name: "Temperature Gauge", parent_topic_id: 4},
  { name: "RPM Indicator", parent_topic_id: 4},
  { name: "Consumption Gauge", parent_topic_id: 4},
  { name: "Fuel Gauge", parent_topic_id: 4},
  { name: "Torque Meter", parent_topic_id: 4},
  { name: "Vibration Monitoring", parent_topic_id: 4},
  { name: "Remote (signal) Transmission System", parent_topic_id: 4},
  { name: "Electronic Displays (ECAM, EICAS)", parent_topic_id: 4}])

Topic.create!([{ name: "Select Sub Topic"},
              {name: "Centre of gravity (cg)", parent_topic_id: 5},
              {name: "Mass and balance limits", parent_topic_id: 5},
              {name: "Terminology", parent_topic_id: 5},
              {name: "Aircraft mass checks", parent_topic_id: 5},
              {name: "Procedures for determining aeroplane mass and balance", parent_topic_id: 5},
              {name: "Effects of overloading", parent_topic_id: 5},
              {name: "Basis of cg calculations (load and balance documentation)", parent_topic_id: 5},
              {name: "Calculation of CG", parent_topic_id: 5},
              {name: "Securing of load CG", parent_topic_id: 5},
              {name: "Area Load, Running Load, Supporting", parent_topic_id: 5}])

Topic.create!([{ name: "Select Sub Topic"},
              {name: "Definitions of terms and speeds used", parent_topic_id: 6},
              {name: "Take-off and landing performance", parent_topic_id: 6},
              {name: "Climb and cruise performance", parent_topic_id: 6},
              {name: "Definitions of terms and speeds", parent_topic_id: 6},
              {name: "Importance of performance calculation", parent_topic_id: 6},
              {name: "Use of performance graphs and tabulated data", parent_topic_id: 6},
              {name: "Take-off", parent_topic_id: 6},
              {name: "Accelerate-stop distance", parent_topic_id: 6},
              {name: "Initial climb", parent_topic_id: 6},
              {name: "Climb", parent_topic_id: 6},
              {name: "Cruise", parent_topic_id: 6},
              {name: "Descent and landing", parent_topic_id: 6},
              {name: "Practical application of an airplane performance manual", parent_topic_id: 6}])

Topic.create!([{ name: "Select Sub Topic"},
              {name: "Navigation plan", parent_topic_id: 7},
              {name: "Fuel plan", parent_topic_id: 7},
              {name: "Flight monitoring and in-flight replanning", parent_topic_id: 7},
              {name: "Radio communication and navigation aids", parent_topic_id: 7},
              {name: "Types of flight plan", parent_topic_id: 7},
              {name: "Completing the flight plan", parent_topic_id: 7},
              {name: "Filing the flight plan", parent_topic_id: 7},
              {name: "Closing the flight plan", parent_topic_id: 7},
              {name: "Adherence to flight plan", parent_topic_id: 7},
              {name: "Chart preparation", parent_topic_id: 7},
              {name: "Navigation plans", parent_topic_id: 7},
              {name: "Simple fuel plans", parent_topic_id: 7},
              {name: "Radio planning practice", parent_topic_id: 7},
              {name: "Meteorological considerations", parent_topic_id: 7},
              {name: "Selection of routes to destination and alternates", parent_topic_id: 7},
              {name: "General flight planning tasks", parent_topic_id: 7},
              {name: "Advanced flight planning aspects for jet aeroplanes", parent_topic_id: 7},
              {name: "Computerised flight planning", parent_topic_id: 7},
              {name: "Extraction of data", parent_topic_id: 7}])